/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-07-23 06:25:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class free_002ddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/bitcamp/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("jar:file:/C:/Users/bitcamp/.m2/repository/net/sargue/java-time-jsptags/2.0.0/java-time-jsptags-2.0.0.jar!/META-INF/javatime.tld", Long.valueOf(1645602756000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1720404962465L));
    _jspx_dependants.put("/WEB-INF/lib/java-time-jsptags-2.0.0.jar", Long.valueOf(1721188174791L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjavatime_005fformat_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjavatime_005fformat_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjavatime_005fformat_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/header.jsp", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <main>\r\n");
      out.write("            <div class=\"container w-50 mt-5 mb-5\">\r\n");
      out.write("                <h4>자유게시글 상세</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"container mt-3 w-50\">\r\n");
      out.write("                <form id=\"modify-form\" action=\"/board/modify.do\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeBoard.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"type\" value=\"free\">\r\n");
      out.write("                    <!--객체 배열 형태의 originFiles 배열을 문자열로 변환하여 input에 담아서 전송-->\r\n");
      out.write("                    <input type=\"hidden\" name=\"originFiles\" id=\"originFiles\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"title\">제목</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"title\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeBoard.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group mt-3\">\r\n");
      out.write("                        <label for=\"nickname\">작성자</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"nickname\" name=\"nickname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeBoard.nickname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group mt-3\">\r\n");
      out.write("                        <label for=\"content\">내용</label>\r\n");
      out.write("                        <textarea class=\"form-control\" id=\"content\" name=\"content\" rows=\"10\" required>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeBoard.content}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group mt-3\">\r\n");
      out.write("                        <label for=\"regdate\">등록일</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"regdate\" name=\"regdate\"\r\n");
      out.write("                               value=\"");
      if (_jspx_meth_javatime_005fformat_005f0(_jspx_page_context))
        return;
      out.write("\" readonly required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group mt-3\">\r\n");
      out.write("                        <label for=\"moddate\">수정일</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"moddate\" name=\"moddate\"\r\n");
      out.write("                               value=\"");
      if (_jspx_meth_javatime_005fformat_005f1(_jspx_page_context))
        return;
      out.write("\" readonly required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group mt-3\">\r\n");
      out.write("                        <label for=\"cnt\">조회수</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"cnt\" name=\"cnt\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeBoard.cnt}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group mt-3\">\r\n");
      out.write("                        <label for=\"uploadFiles\">파일첨부</label>\r\n");
      out.write("                        <input class=\"form-control\" type=\"file\" name=\"uploadFiles\" id=\"uploadFiles\" multiple>\r\n");
      out.write("                        <div id=\"image-preview\">\r\n");
      out.write("                            <input type=\"file\" id=\"changeFiles\" name=\"changeFiles\" style=\"display: none;\"\r\n");
      out.write("                                   multiple>\r\n");
      out.write("                            <p style=\"color: red; font-size:0.9rem;\">\r\n");
      out.write("                                파일을 변경하려면 이미지를 클릭하세요. 파일을 다운로드하려면 파일이름을 클릭하세요. 파일을 추가하려면 파일 선택 버튼을 클릭하세요.\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <div id=\"preview\" class=\"mt-3 text-center\"\r\n");
      out.write("                                 data-placeholder=\"파일을 첨부하려면 파일선택 버튼을 누르세요.\">\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/footer.jsp", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        // 추가된 파일들을 담아줄 배열\r\n");
      out.write("        const uploadFiles = [];\r\n");
      out.write("\r\n");
      out.write("        // 기존에 업로도되어 있는 파일들을 담아줄 배열\r\n");
      out.write("        // 게시글번호, 파일번호, 파일명을 객체 형태로 담아준다.\r\n");
      out.write("        const originFiles = [];\r\n");
      out.write("\r\n");
      out.write("        // 변경된 파일들을 담아줄 배열\r\n");
      out.write("        const changeFiles = [];\r\n");
      out.write("\r\n");
      out.write("        $(() => {\r\n");
      out.write("            $(\"#modify-form\").on(\"submit\", (e) => {\r\n");
      out.write("                $(\"#regdate\").val(`${$(\"#regdate\").val()}T00:00:00`);\r\n");
      out.write("                $(\"#moddate\").val(`${$(\"#moddate\").val()}T00:00:00`);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // 업로드되어 있던 파일들을 originFiles 배열에 담기\r\n");
      out.write("            for(let i = 0; i < $(\"#filecnt\").val(); i++) {\r\n");
      out.write("                const originFileObj = {\r\n");
      out.write("                    board_id: $(\"input[name='id']\").val(),\r\n");
      out.write("                    id: $(\"#fileId\" + i).val(),\r\n");
      out.write("                    filename: $(\"#filename\" + i).val(),\r\n");
      out.write("                    filestatus: \"N\" // 초기상태 변경없음: N, 변경되면: U, 삭제되면: D\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                originFiles.push(originFileObj);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $(\"#uploadFiles\").on(\"change\", (e) => {\r\n");
      out.write("                // input에 추가된 파일들 변수로 받기\r\n");
      out.write("                const files = e.target.files;\r\n");
      out.write("\r\n");
      out.write("                // 변수로 받아온 파일들 배열로 변환\r\n");
      out.write("                const fileArr = Array.prototype.slice.call(files);\r\n");
      out.write("\r\n");
      out.write("                for(file of fileArr) {\r\n");
      out.write("                    // 미리보기 메소드 호출\r\n");
      out.write("                    imageLoader(file);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // modify-form이 서브밋될 때\r\n");
      out.write("            // uploadFiles 배열에 담겨있는 파일들을 input name=\"uploadFiles\"에 담기\r\n");
      out.write("            // changeFiles 배열에 담겨있는 파일들을 input name=\"changeFiles\"에 담기\r\n");
      out.write("            // originFiles 배열에 담겨있는 객체들을 문자열로 변환하여 input name=\"originFiles\"에 담기\r\n");
      out.write("            $(\"#modify-form\").on(\"submit\", (e) => {\r\n");
      out.write("                let dataTransfer1 = new DataTransfer();\r\n");
      out.write("                let dataTransfer2 = new DataTransfer();\r\n");
      out.write("\r\n");
      out.write("                for(i in uploadFiles) {\r\n");
      out.write("                    const file = uploadFiles[i];\r\n");
      out.write("                    dataTransfer1.items.add(file);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                $(\"#uploadFiles\")[0].files = dataTransfer1.files;\r\n");
      out.write("\r\n");
      out.write("                for(i in changeFiles) {\r\n");
      out.write("                    const file = changeFiles[i];\r\n");
      out.write("                    dataTransfer2.items.add(file);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                $(\"#changeFiles\")[0].files = dataTransfer2.files;\r\n");
      out.write("\r\n");
      out.write("                $(\"#originFiles\").val(JSON.stringify(originFiles));\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 업로도되어 있어서 표출되어 있는 파일들을 클릭했을 때 실행될 메소드\r\n");
      out.write("        const fileClick = (fileId) => {\r\n");
      out.write("            $(\"#changeFile\" + fileId).click();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        const changFile = (fileId, e) => {\r\n");
      out.write("            const files = e.target.files;\r\n");
      out.write("\r\n");
      out.write("            const fileArr = Array.prototype.slice.call(files);\r\n");
      out.write("\r\n");
      out.write("            changeFiles.push(fileArr[0]);\r\n");
      out.write("\r\n");
      out.write("            const reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("            reader.onload = (event) => {\r\n");
      out.write("                const img = document.getElementById(\"img\" + fileId);\r\n");
      out.write("                const p = document.getElementById(\"filename\" + fileId);\r\n");
      out.write("\r\n");
      out.write("                if(fileArr[0].name.match(/(.*?)\\.(jpg|jpeg|png|gif|bmp)$/)) {\r\n");
      out.write("                    img.src = event.target.result;\r\n");
      out.write("                } else {\r\n");
      out.write("                    img.src = \"/static/images/defaultFileImg.png\";\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                p.textContent = fileArr[0].name;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            reader.readAsDataURL(fileArr[0]);\r\n");
      out.write("\r\n");
      out.write("            // 기존에 originFiles 배열에 담겨있던 내용 변경\r\n");
      out.write("            for(let i = 0; i < originFiles.length; i++) {\r\n");
      out.write("                if(fileId == originFiles[i].id) {\r\n");
      out.write("                    originFiles[i].filestatus = \"U\";\r\n");
      out.write("                    originFiles[i].newfilename = fileArr[0].name;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        const deleteFile = (e) => {\r\n");
      out.write("            // 클릭된 x 버튼 변수로 담기\r\n");
      out.write("            const element = e.target;\r\n");
      out.write("\r\n");
      out.write("            const deleteFileId = element.getAttribute(\"deleteFile\");\r\n");
      out.write("\r\n");
      out.write("            // originFiles 배열에서 deleteFileId와 id가 같은 객체의 filestatus를 D로 변경\r\n");
      out.write("            for(let i = 0; i < originFiles.length; i++) {\r\n");
      out.write("                if(deleteFileId == originFiles[i].id) {\r\n");
      out.write("                    originFiles[i].filestatus = \"D\";\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // 부모 div 삭제\r\n");
      out.write("            const parentDiv = element.parentNode;\r\n");
      out.write("            $(parentDiv).remove();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 미리보기 처리하는 메소드\r\n");
      out.write("        // 미리보기될 파일은 서버나 데이터베이스에 저장된 상태가 아니기 때문에\r\n");
      out.write("        // 파일 자체를 Base64 인코딩 방식으로 문자열로 변환해서 이미지로 호출해야 된다.\r\n");
      out.write("        // 이미지가 들어갈 태그 생성과 파일을 Base64 인코딩\r\n");
      out.write("        const imageLoader = (file) => {\r\n");
      out.write("            // 추가된 파일 uploadFiles 배열에 담기\r\n");
      out.write("            uploadFiles.push(file);\r\n");
      out.write("\r\n");
      out.write("            let reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("            // reader가 호출되면 실행될 이벤트 등록\r\n");
      out.write("            reader.onload = (e) => {\r\n");
      out.write("                // 이미지를 표출할 img 태그 생성\r\n");
      out.write("                let img = document.createElement(\"img\");\r\n");
      out.write("\r\n");
      out.write("                img.classList.add(\"upload-file\");\r\n");
      out.write("\r\n");
      out.write("                // 이미지인지 아닌지 판단\r\n");
      out.write("                if(file.name.toLowerCase().match(/(.*?)\\.(jpg|jpeg|png|gif|svg|bmp)$/)) {\r\n");
      out.write("                    img.src = e.target.result;\r\n");
      out.write("                } else {\r\n");
      out.write("                    img.src = \"/static/images/defaultFileImg.png\";\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 미리보기 영역에 추가\r\n");
      out.write("                // makeDiv 메소드를 호출해서 만들어진 div 자체를 preview 영역에 추가\r\n");
      out.write("                $(\"#preview\").append(makeDiv(img, file));\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // 파일을 Base64인코딩된 문자열로 로드\r\n");
      out.write("            // 이 메소드가 실행되면서 위에서 등록한 onload 이벤트가 함께 동작한다.\r\n");
      out.write("            reader.readAsDataURL(file);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 미리보기 영역에 추가될 div를 생성하는 메소드\r\n");
      out.write("        const makeDiv = (img, file) => {\r\n");
      out.write("            let div = document.createElement(\"div\");\r\n");
      out.write("\r\n");
      out.write("            div.classList.add(\"upload-file-div\");\r\n");
      out.write("\r\n");
      out.write("            // 삭제 버튼 추가\r\n");
      out.write("            let btn = document.createElement(\"input\");\r\n");
      out.write("\r\n");
      out.write("            btn.classList.add(\"upload-file-delete-btn\");\r\n");
      out.write("\r\n");
      out.write("            btn.setAttribute(\"type\", \"button\");\r\n");
      out.write("            btn.setAttribute(\"value\", \"x\");\r\n");
      out.write("            // 사용자 정의 속성 추가\r\n");
      out.write("            btn.setAttribute(\"deleteFile\", file.name);\r\n");
      out.write("\r\n");
      out.write("            // x 버튼에 클릭했을 때 삭제하는 기능 추가\r\n");
      out.write("            btn.onclick = (e) => {\r\n");
      out.write("                // 클릭된 버튼 변수로 받기\r\n");
      out.write("                const element = e.target;\r\n");
      out.write("\r\n");
      out.write("                const deleteFileName = element.getAttribute(\"deleteFile\");\r\n");
      out.write("\r\n");
      out.write("                // 배열에서 파일 삭제\r\n");
      out.write("                for(let i = 0; i < uploadFiles.length; i++) {\r\n");
      out.write("                    if(deleteFileName === uploadFiles[i].name) {\r\n");
      out.write("                        uploadFiles.splice(i, 1);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                // uploadFiles.filter(((file, index) => file.name != deleteFileName || uploadFiles.indexOf(file) != index));\r\n");
      out.write("\r\n");
      out.write("                // input에서도 파일 삭제\r\n");
      out.write("                // input type=\"file\"은 첨부된 파일들을 fileList 형태로 관리\r\n");
      out.write("                // fileList는 File 객체에 바로 담을수 없기 때문에\r\n");
      out.write("                // DataTransfer라는 클래스를 사용해서 변환 후에 담아줘야한다.\r\n");
      out.write("                let dataTransfer = new DataTransfer();\r\n");
      out.write("\r\n");
      out.write("                for(i in uploadFiles) {\r\n");
      out.write("                    // uploadFiles 배열에 있는 File 객체를 하나씩 DataTransfer 객체에 담아준다.\r\n");
      out.write("                    const file = uploadFiles[i];\r\n");
      out.write("                    dataTransfer.items.add(file);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // input type=\"file\"에 fileList 형태로 밀어넣기\r\n");
      out.write("                $(\"#uploadFiles\")[0].files = dataTransfer.files;\r\n");
      out.write("\r\n");
      out.write("                // 클릭된 btn 태그를 소유하고 있는 부모 div 태그 삭제\r\n");
      out.write("                const parentDiv = element.parentNode;\r\n");
      out.write("                $(parentDiv).remove();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // 파일 이름을 표출할 p 태그 생성\r\n");
      out.write("            let p = document.createElement(\"p\");\r\n");
      out.write("\r\n");
      out.write("            p.classList.add(\"upload-file-name\");\r\n");
      out.write("\r\n");
      out.write("            p.textContent = file.name;\r\n");
      out.write("\r\n");
      out.write("            // div태그에 img, btn, p 태그 자식으로 추가\r\n");
      out.write("            div.appendChild(img);\r\n");
      out.write("            div.appendChild(btn);\r\n");
      out.write("            div.appendChild(p);\r\n");
      out.write("\r\n");
      out.write("            return div;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_javatime_005fformat_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  javatime:format
    net.sargue.time.jsptags.FormatTag _jspx_th_javatime_005fformat_005f0 = (net.sargue.time.jsptags.FormatTag) _005fjspx_005ftagPool_005fjavatime_005fformat_0026_005fvalue_005fpattern_005fnobody.get(net.sargue.time.jsptags.FormatTag.class);
    boolean _jspx_th_javatime_005fformat_005f0_reused = false;
    try {
      _jspx_th_javatime_005fformat_005f0.setPageContext(_jspx_page_context);
      _jspx_th_javatime_005fformat_005f0.setParent(null);
      // /WEB-INF/views/board/free-detail.jsp(44,38) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_javatime_005fformat_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeBoard.regdate}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/board/free-detail.jsp(44,38) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_javatime_005fformat_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_javatime_005fformat_005f0 = _jspx_th_javatime_005fformat_005f0.doStartTag();
      if (_jspx_th_javatime_005fformat_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fjavatime_005fformat_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_javatime_005fformat_005f0);
      _jspx_th_javatime_005fformat_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_javatime_005fformat_005f0, _jsp_getInstanceManager(), _jspx_th_javatime_005fformat_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_javatime_005fformat_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  javatime:format
    net.sargue.time.jsptags.FormatTag _jspx_th_javatime_005fformat_005f1 = (net.sargue.time.jsptags.FormatTag) _005fjspx_005ftagPool_005fjavatime_005fformat_0026_005fvalue_005fpattern_005fnobody.get(net.sargue.time.jsptags.FormatTag.class);
    boolean _jspx_th_javatime_005fformat_005f1_reused = false;
    try {
      _jspx_th_javatime_005fformat_005f1.setPageContext(_jspx_page_context);
      _jspx_th_javatime_005fformat_005f1.setParent(null);
      // /WEB-INF/views/board/free-detail.jsp(49,38) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_javatime_005fformat_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeBoard.moddate}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/board/free-detail.jsp(49,38) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_javatime_005fformat_005f1.setPattern("yyyy-MM-dd");
      int _jspx_eval_javatime_005fformat_005f1 = _jspx_th_javatime_005fformat_005f1.doStartTag();
      if (_jspx_th_javatime_005fformat_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fjavatime_005fformat_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_javatime_005fformat_005f1);
      _jspx_th_javatime_005fformat_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_javatime_005fformat_005f1, _jsp_getInstanceManager(), _jspx_th_javatime_005fformat_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/board/free-detail.jsp(66,32) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/free-detail.jsp(66,32) '${fileList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${fileList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/board/free-detail.jsp(66,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("file");
      // /WEB-INF/views/board/free-detail.jsp(66,32) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                    <div class=\"upload-file-div\">\r\n");
            out.write("                                        <input type=\"hidden\" id=\"fileId");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                        <input type=\"hidden\" id=\"filename");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.filename}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                        <!--밑에 표시된 파일을 클릭했을 때 파일 선택창이 뜨도록 input type=\"file\" 하나 생성-->\r\n");
            out.write("                                        <input type=\"file\" id=\"changeFile");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" name=\"changeFile");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"display: none;\"\r\n");
            out.write("                                               onchange=\"changFile(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(", event)\">\r\n");
            out.write("                                        ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                                        ");
            if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                                        <input type=\"button\" value=\"x\"\r\n");
            out.write("                                               deleteFile=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("                                               class=\"upload-file-delete-btn\"\r\n");
            out.write("                                               onclick=\"deleteFile(event)\">\r\n");
            out.write("                                        <p id=\"filename");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("                                           class=\"upload-file-name\">\r\n");
            out.write("                                            ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.fileoriginname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("                                        </p>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/board/free-detail.jsp(73,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.last}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <input type=\"hidden\" id=\"filecnt\" name=\"filecnt\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/board/free-detail.jsp(77,44) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.filetype eq 'image'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                <img id=\"img");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                                     src=\"/upload/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.filename}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                                     class=\"upload-file\"\r\n");
          out.write("                                                     alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.fileoriginname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                                     onclick=\"fileClick(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">\r\n");
          out.write("                                            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                <img id=\"img");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                                     src=\"/static/images/defaultFileImg.png\"\r\n");
          out.write("                                                     class=\"upload-file\"\r\n");
          out.write("                                                     alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.fileoriginname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                                     onclick=\"fileClick(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">\r\n");
          out.write("                                            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/board/free-detail.jsp(105,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember ne null and loginMember.id eq freeBoard.WRITER_ID}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <div class=\"container mt-3 mb-5 w-50 text-center\">\r\n");
          out.write("                            <button type=\"submit\" id=\"btn-update\" class=\"btn btn-outline-secondary\">수정</button>\r\n");
          out.write("                            <button type=\"button\" id=\"btn-delete\" class=\"btn btn-outline-secondary ml-2\" onclick=\"location.href='/board/delete.do?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freeBoard.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&type=free'\">삭제</button>\r\n");
          out.write("                        </div>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
